// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP-GkPsscNopK406bL5CvtaSVkCWHNlYI',
    appId: '1:497551816888:web:0a22520b4c1d68768b5c4d',
    messagingSenderId: '497551816888',
    projectId: 'my-portfolio-app-f1fa8',
    authDomain: 'my-portfolio-app-f1fa8.firebaseapp.com',
    storageBucket: 'my-portfolio-app-f1fa8.appspot.com',
    measurementId: 'G-G8X4EGJ5VZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3xPegKLcpJGxUXG7f-mttMNxpNDVoCpo',
    appId: '1:497551816888:android:4f1d82f4f29a672f8b5c4d',
    messagingSenderId: '497551816888',
    projectId: 'my-portfolio-app-f1fa8',
    storageBucket: 'my-portfolio-app-f1fa8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKNevvnVJFEKVLBk7K7PCKGo337bGpULM',
    appId: '1:497551816888:ios:f6284d8efd464ed58b5c4d',
    messagingSenderId: '497551816888',
    projectId: 'my-portfolio-app-f1fa8',
    storageBucket: 'my-portfolio-app-f1fa8.appspot.com',
    iosBundleId: 'com.example.myPortfolioApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKNevvnVJFEKVLBk7K7PCKGo337bGpULM',
    appId: '1:497551816888:ios:f6284d8efd464ed58b5c4d',
    messagingSenderId: '497551816888',
    projectId: 'my-portfolio-app-f1fa8',
    storageBucket: 'my-portfolio-app-f1fa8.appspot.com',
    iosBundleId: 'com.example.myPortfolioApp',
  );
}
